title: "Benjamin Wojtecki"
description: "Site personnel et tutoriels"
theme: minima   # (optionnel : un thème de base fourni par GitHub Pages)

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Empêche Jekyll d'ignorer certains fichiers
include:
  - index.html
  - Pac_Bayes_Bound.md
  - math.md
